# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b02b50f0d041e6b665666d92ffe783fc65199279abb494142856d4525d7f4417a5898b108abb744a8fd5cea87ae7faa38fe509a0658d708db9d7efd23b8d3e

test:
  secret_key_base: a30fc9f0daf86ca93a99d81be6d4783b3bbaceecb10dd9afa3bae9cc64496edee2010b8edc32db08840376db5f886f2b35d20a69f43e410052501cab6bedb460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
